app:
  name: "CryptoMART"
  domain: "cryptomart.us"
  subdomain: "exchange"
render_protect: false
ssl:
  enabled: false    # Make sure to enable during deployment
  email: "bash.forger@gmail.com"
images:
  peatio: rubykube/peatio:2.3.43
  barong: rubykube/barong:2.3.36
  frontend: quay.io/openware/baseapp:2.3.20 # Check on quay.io/openware for latest tags
  tower: quay.io/openware/tower-lite:2.3.130
  postmaster: quay.io/openware/postmaster:2.3.5
arke_proxy:
  enabled: false
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  mode: development
  token: changeme
storage:
  provider: "Google"
  bucketName: "opendax-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "v2"
  siteKey: "6LewvcsUAAAAAOFFpn2UI14iXObz_zgtHBXmDCIt"
  secretKey: "6LewvcsUAAAAAFfoXC8Zgh4Y-v0mzQgyh-e01zVu"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "0x1C9bDE003E47c2a797a0dB3C765356F938e00118"
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "0x1C9bDE003E47c2a797a0dB3C765356F938e00118"
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "0xF6d1398d12544423eA87fe0790e313cacC856d72"
    max_balance: 1000.0
    secret: changeme
  - kind: fee
    address: "0xdFb842793275B1B68bfBB74f7BeDF67bDCd95227"
    max_balance: 1000.0
    secret: changeme
  - kind: cold
    address: "0xfC49E51e5D36797e6Fc2DC89748d740aADa38Fa7"
    max_balance: 1000.0
    secret: changeme
  
terraform:
  credentials: "~/safe/opendax.json"
  project: "example-opendax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "opendax-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"

